In [ ]:
import pandas as pd
import pyarrow.dataset as ds

In [ ]:
dataset = ds.dataset("/mnt/idms/home/magyary/rrbs_human_embryo/data/smith/processed/cpgs_5_cov.parquet", format="parquet")
table = dataset.to_table()
df = table.to_pandas().sample(n=1000, random_state=42)
df

,chromosome,pos,hESp1-E4,hICM-1,hESp5-E4,hESp0-E1,hICM-2,hBlast-1,hSperm-533-90,hESp0-E4,...,hBlast-2,hESp5-E5,hBlast-3,hSperm-530-90,hTE-2,hESp1-E5,hTE-1,hSperm-534-90,hBlastSingle-5,h8c-1
1594976,chr11,30607691,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000,0.000000,...,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,NaN,0.000000
41581,chr1,10269003,0.280000,0.133333,0.200000,0.615385,0.000000,0.1,NaN,0.705882,...,0.200000,NaN,0.285714,0.333333,0.047619,0.571429,0.000000,0.3,0.000000,0.142857
2926242,chrX,55066102,0.910256,0.177778,0.928571,0.970149,0.000000,0.0,0.833333,0.912281,...,0.285714,0.857143,0.318182,0.846154,0.133333,1.000000,0.347826,0.5,0.029412,0.362069
573570,chr3,169781668,0.875000,0.230769,NaN,0.909091,0.176471,NaN,NaN,0.777778,...,0.625000,NaN,0.600000,0.000000,0.400000,1.000000,0.187500,0.0,0.000000,NaN
1930113,chr14,59950571,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000,0.000000,...,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2556779,chr19,17438314,0.657143,0.210526,0.333333,0.640000,0.000000,NaN,NaN,0.378378,...,NaN,NaN,NaN,0.000000,0.000000,0.520000,0.111111,0.0,0.037037,0.000000
452764,chr2,241331303,0.727273,0.333333,NaN,1.000000,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.750000,0.200000,NaN,0.000000,0.000000
1554781,chr10,135171502,0.000000,0.000000,NaN,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
898587,chr6,31869119,0.117647,0.100000,0.250000,0.086957,0.000000,0.0,0.000000,0.125000,...,0.000000,0.090909,0.000000,0.000000,0.000000,0.125000,0.000000,0.0,0.000000,NaN
1764855,chr12,70024545,0.689655,0.000000,NaN,0.961538,0.000000,0.0,NaN,0.850000,...,0.000000,NaN,0.142857,1.000000,0.133333,1.000000,NaN,1.0,0.000000,0.000000

In [ ]:
df.to_parquet("/mnt/idms/home/magyary/bs-cpg/data/sample_cpg_df.parquet")